# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdbe350049582c3a3847d6bba5956071965919e1689efa4fa9387746e79e17c4c65a10c851fa1607377ff25215efa8a680177aae32eb0330079dcfafa133d3bf

test:
  secret_key_base: 6a2914fcc0396df7d5d75c5c7e8201ad52e8e1a45e200d8ff52b270e60f7a910f267fe5bba088f0011bc1f99a06ecb8dd64f9b2df3f802a25603be623f801a71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
